application: trust-pad
version: alpha-001
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static
