runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /privacy
  static_files: privacy.html
  upload: privacy.html

- url: /.*
  static_files: index.html
  upload: index.html
  secure: always
